//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSay.UI.Tests {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class TestResources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal TestResources() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeSay.UI.Tests.TestResources", typeof(TestResources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to # SOME DESCRIPTIVE TITLE.
		///# Copyright (C) YEAR THE PACKAGE&apos;S COPYRIGHT HOLDER
		///# This file is distributed under the same license as the PACKAGE package.
		///# FIRST AUTHOR &lt;EMAIL@ADDRESS&gt;, YEAR.
		///#
		///#, fuzzy
		///msgid &quot;&quot;
		///msgstr &quot;&quot;
		///&quot;Project-Id-Version: PACKAGE VERSION\n&quot;
		///&quot;Report-Msgid-Bugs-To: martin@godisch.de\n&quot;
		///&quot;POT-Creation-Date: 2005-09-20 20:52+0200\n&quot;
		///&quot;PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n&quot;
		///&quot;Last-Translator: FULL NAME &lt;EMAIL@ADDRESS&gt;\n&quot;
		///&quot;Language-Team: LANGUAGE &lt;LL@li.org&gt;\n&quot;
		///&quot;MIME-Version: 1.0 [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string poStrings {
			get {
				return ResourceManager.GetString("poStrings", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
		///&lt;prefs analysisWritingSystem=&quot;ANA&quot; vernacularWritingSystem=&quot;VER&quot;&gt;
		///&lt;writingSystem id=&quot;ANA&quot;&gt;
		///  &lt;font name=&quot;WingDings&quot; baseSize=&quot;20&quot;/&gt;
		///&lt;/writingSystem&gt;
		///  &lt;writingSystem id=&quot;VER&quot;&gt;
		///    &lt;font name=&quot;WingDings&quot; baseSize=&quot;20&quot;/&gt;
		///  &lt;/writingSystem&gt;
		///&lt;/prefs&gt;.
		/// </summary>
		internal static string WritingSystemPrefs {
			get {
				return ResourceManager.GetString("WritingSystemPrefs", resourceCulture);
			}
		}
	}
}
