//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSay.CommonTools.Properties {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Resources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeSay.CommonTools.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		public static System.Drawing.Bitmap blueDictionary {
			get {
				object obj = ResourceManager.GetObject("blueDictionary", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		public static System.Drawing.Bitmap blueWeSay {
			get {
				object obj = ResourceManager.GetObject("blueWeSay", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		public static System.Drawing.Bitmap emailAction {
			get {
				object obj = ResourceManager.GetObject("emailAction", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		public static System.Drawing.Bitmap greenEmail {
			get {
				object obj = ResourceManager.GetObject("greenEmail", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		public static System.Drawing.Bitmap greenPrinter {
			get {
				object obj = ResourceManager.GetObject("greenPrinter", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		public static System.Drawing.Bitmap greenSynchronize {
			get {
				object obj = ResourceManager.GetObject("greenSynchronize", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		public static System.Drawing.Bitmap greenUsbKey {
			get {
				object obj = ResourceManager.GetObject("greenUsbKey", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		public static System.Drawing.Bitmap printAction {
			get {
				object obj = ResourceManager.GetObject("printAction", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		public static System.Drawing.Bitmap WeSay64x64 {
			get {
				object obj = ResourceManager.GetObject("WeSay64x64", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
