//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Addin.LiftReports.Properties
{
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[DebuggerNonUserCode]
	[CompilerGenerated]
	internal class Resources
	{
		private static ResourceManager resourceMan;

		private static CultureInfo resourceCulture;

		[SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		internal static ResourceManager ResourceManager
		{
			get
			{
				if (ReferenceEquals(resourceMan, null))
				{
					ResourceManager temp =
							new ResourceManager("Addin.LiftReports.Properties.Resources",
												typeof (Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		internal static CultureInfo Culture
		{
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		internal static Bitmap image
		{
			get
			{
				object obj = ResourceManager.GetObject("image", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
		///&lt;HTML&gt;
		///&lt;HEAD&gt;
		///	&lt;META HTTP-EQUIV=&quot;CONTENT-TYPE&quot; CONTENT=&quot;text/html; charset=windows-1252&quot;&gt;
		///	&lt;TITLE&gt;&lt;/TITLE&gt;
		///	&lt;META NAME=&quot;GENERATOR&quot; CONTENT=&quot;OpenOffice.org 2.0  (Win32)&quot;&gt;
		///	&lt;META NAME=&quot;CREATED&quot; CONTENT=&quot;20070511;12454487&quot;&gt;
		///	&lt;META NAME=&quot;CHANGED&quot; CONTENT=&quot;20070511;14221334&quot;&gt;
		///	&lt;STYLE&gt;
		///	&lt;!--
		///		@page { size: 8.5in 11in; margin: 0.79in }
		///		P { margin-bottom: 0.08in }
		///	--&gt;
		///	&lt;/STYLE&gt;
		///&lt;/HEAD&gt;
		///&lt;BODY LANG=&quot;en-US&quot; DIR=&quot;LTR&quot;&gt;
		///&lt;P STYLE=&quot;margin-b [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string reportTemplate
		{
			get { return ResourceManager.GetString("reportTemplate", resourceCulture); }
		}

		internal static Bitmap WeSay
		{
			get
			{
				object obj = ResourceManager.GetObject("WeSay", resourceCulture);
				return ((Bitmap) (obj));
			}
		}
	}
}