//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace WeSay.App.Properties
{
	[CompilerGenerated()]
	[GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator",
			"8.0.0.0")]
	internal sealed partial class Settings: ApplicationSettingsBase
	{
		private static Settings defaultInstance = ((Settings) (Synchronized(new Settings())));

		public static Settings Default
		{
			get { return defaultInstance; }
		}

		[UserScopedSetting()]
		[DebuggerNonUserCode()]
		[DefaultSettingValue("")]
		public string CurrentWorkTask
		{
			get { return ((string) (this["CurrentWorkTask"])); }
			set { this["CurrentWorkTask"] = value; }
		}

		[UserScopedSetting()]
		[DebuggerNonUserCode()]
		[DefaultSettingValue("True")]
		public bool NeedUpgrade
		{
			get { return ((bool) (this["NeedUpgrade"])); }
			set { this["NeedUpgrade"] = value; }
		}

		[UserScopedSetting()]
		[DebuggerNonUserCode()]
		[DefaultSettingValue("")]
		public string PreviousLiftPath
		{
			get { return ((string) (this["PreviousLiftPath"])); }
			set { this["PreviousLiftPath"] = value; }
		}

		[UserScopedSetting()]
		[DebuggerNonUserCode()]
		[DefaultSettingValue("")]
		public string SkinName
		{
			get { return ((string) (this["SkinName"])); }
			set { this["SkinName"] = value; }
		}
	}
}