//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace WeSay.Foundation.Tests
{
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[DebuggerNonUserCode]
	[CompilerGenerated]
	internal class TestResources
	{
		private static ResourceManager resourceMan;

		private static CultureInfo resourceCulture;

		[SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal TestResources() {}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		internal static ResourceManager ResourceManager
		{
			get
			{
				if (ReferenceEquals(resourceMan, null))
				{
					ResourceManager temp =
							new ResourceManager("WeSay.Foundation.Tests.TestResources",
												typeof (TestResources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		internal static CultureInfo Culture
		{
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
		///&lt;WritingSystemCollection&gt;
		///  &lt;members&gt;
		///    &lt;WritingSystem&gt;
		///      &lt;FontName&gt;Courier New&lt;/FontName&gt;
		///      &lt;FontSize&gt;10&lt;/FontSize&gt;
		///      &lt;Id&gt;PretendAnalysis&lt;/Id&gt;
		///    &lt;/WritingSystem&gt;
		///    &lt;WritingSystem&gt;
		///      &lt;FontName&gt;Courier New&lt;/FontName&gt;
		///      &lt;FontSize&gt;20&lt;/FontSize&gt;
		///      &lt;Id&gt;PretendVernacular&lt;/Id&gt;
		///    &lt;/WritingSystem&gt;
		///  &lt;/members&gt;
		///&lt;/WritingSystemCollection&gt;.
		/// </summary>
		internal static string WritingSystemPrefs
		{
			get { return ResourceManager.GetString("WritingSystemPrefs", resourceCulture); }
		}
	}
}