# -*- mode: ruby -*-
# vi: set ft=ruby :

# http://stackoverflow.com/a/17729961/35577
# pref_interface = ['eth0', 'eth1', 'eth2', 'en0' ]
# vm_interfaces = %x( VBoxManage list bridgedifs | grep ^Name).gsub(/Name:\s+/,'')
# pref_interface = pref_interface.map {|n| n if vm_interfaces.include?(n)}.compact
# $network_interface=pref_interface[0]

required_plugins = ["vagrant-vbguest", "vagrant-cachier"]
unless (missing_plugins = required_plugins.select { |p| !Vagrant.has_plugin?(p) }).empty?
  raise "\nBefore you can 'vagrant up' this box, please install these plugins\n  " +
        missing_plugins.join("\n  ") +
        "\nTypically this is done by running\n" +
        "  'vagrant plugin install <plugin>'\nfor each plugin"
end

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  def bootstrap_wesay(config, name, gui)
    config.vm.provision :shell, :path => 'bootstrap.sh'
    config.vm.synced_folder '..', '/wesay'
    config.vm.provider :virtualbox do |vb|
      vb.gui=gui
      vb.name=name
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    # vagrant-cachier setting
    config.cache.scope = :box
end

  config.vm.define :wasta do |wasta|
    wasta.vm.box='wasta-2014-01-23'
    wasta.vm.box_url='http://goo.gl/kifxgv'
    bootstrap_wesay wasta, 'vagrant-wasta', true
  end

  config.vm.define :precise64 do |precise64|
    precise64.vm.box='precise64-unity'
    precise64.vm.box_url='http://goo.gl/B0e64k'
    bootstrap_wesay precise64, 'vagrant-precise64', true
  end
end
