//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSay.ConfigTool.Properties {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeSay.ConfigTool.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		internal static System.Drawing.Bitmap about {
			get {
				object obj = ResourceManager.GetObject("about", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap buttonImage {
			get {
				object obj = ResourceManager.GetObject("buttonImage", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap chorus {
			get {
				object obj = ResourceManager.GetObject("chorus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap ConfigActions {
			get {
				object obj = ResourceManager.GetObject("ConfigActions", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap ConfigBackup {
			get {
				object obj = ResourceManager.GetObject("ConfigBackup", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap ConfigFields {
			get {
				object obj = ResourceManager.GetObject("ConfigFields", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap ConfigInterfaceLanguage {
			get {
				object obj = ResourceManager.GetObject("ConfigInterfaceLanguage", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap ConfigOptionLists {
			get {
				object obj = ResourceManager.GetObject("ConfigOptionLists", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap ConfigTasks {
			get {
				object obj = ResourceManager.GetObject("ConfigTasks", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap ConfigWritingSystems {
			get {
				object obj = ResourceManager.GetObject("ConfigWritingSystems", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap construction {
			get {
				object obj = ResourceManager.GetObject("construction", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap deleteOptionListItem {
			get {
				object obj = ResourceManager.GetObject("deleteOptionListItem", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap genericAction {
			get {
				object obj = ResourceManager.GetObject("genericAction", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap GenericLittleDeletionButton {
			get {
				object obj = ResourceManager.GetObject("GenericLittleDeletionButton", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap genericLittleNewButton {
			get {
				object obj = ResourceManager.GetObject("genericLittleNewButton", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap NewOptionListItem {
			get {
				object obj = ResourceManager.GetObject("NewOptionListItem", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap NewOptionsList {
			get {
				object obj = ResourceManager.GetObject("NewOptionsList", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap NewProject {
			get {
				object obj = ResourceManager.GetObject("NewProject", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap openOptionsList {
			get {
				object obj = ResourceManager.GetObject("openOptionsList", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap openProject {
			get {
				object obj = ResourceManager.GetObject("openProject", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap WelcomeImage {
			get {
				object obj = ResourceManager.GetObject("WelcomeImage", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Icon WeSayApplicationIcon {
			get {
				object obj = ResourceManager.GetObject("WeSayApplicationIcon", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}

		internal static System.Drawing.Bitmap WeSayConfigMenuSized {
			get {
				object obj = ResourceManager.GetObject("WeSayConfigMenuSized", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap WeSayImage {
			get {
				object obj = ResourceManager.GetObject("WeSayImage", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap WeSayMenuSized {
			get {
				object obj = ResourceManager.GetObject("WeSayMenuSized", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Icon WeSaySetupApplicationIcon {
			get {
				object obj = ResourceManager.GetObject("WeSaySetupApplicationIcon", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}

		internal static System.Drawing.Bitmap WeSaySetupImage {
			get {
				object obj = ResourceManager.GetObject("WeSaySetupImage", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
