//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace WeSay.ConfigTool.Properties
{
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[DebuggerNonUserCode()]
	[CompilerGenerated()]
	internal class Resources
	{
		private static ResourceManager resourceMan;

		private static CultureInfo resourceCulture;

		[SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		internal static ResourceManager ResourceManager
		{
			get
			{
				if (ReferenceEquals(resourceMan, null))
				{
					ResourceManager temp =
							new ResourceManager("WeSay.ConfigTool.Properties.Resources",
												typeof (Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		internal static CultureInfo Culture
		{
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		internal static Bitmap about
		{
			get
			{
				object obj = ResourceManager.GetObject("about", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap buttonImage
		{
			get
			{
				object obj = ResourceManager.GetObject("buttonImage", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static System.Drawing.Bitmap chorus {
			get {
				object obj = ResourceManager.GetObject("chorus", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap ConfigActions {
			get {
				object obj = ResourceManager.GetObject("ConfigActions", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap ConfigBackup
		{
			get
			{
				object obj = ResourceManager.GetObject("ConfigBackup", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap ConfigFields
		{
			get
			{
				object obj = ResourceManager.GetObject("ConfigFields", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap ConfigInterfaceLanguage
		{
			get
			{
				object obj = ResourceManager.GetObject("ConfigInterfaceLanguage", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap ConfigOptionLists
		{
			get
			{
				object obj = ResourceManager.GetObject("ConfigOptionLists", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap ConfigTasks
		{
			get
			{
				object obj = ResourceManager.GetObject("ConfigTasks", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap ConfigWritingSystems
		{
			get
			{
				object obj = ResourceManager.GetObject("ConfigWritingSystems", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap construction
		{
			get
			{
				object obj = ResourceManager.GetObject("construction", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap deleteOptionListItem
		{
			get
			{
				object obj = ResourceManager.GetObject("deleteOptionListItem", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap genericAction
		{
			get
			{
				object obj = ResourceManager.GetObject("genericAction", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap GenericLittleDeletionButton
		{
			get
			{
				object obj =
						ResourceManager.GetObject("GenericLittleDeletionButton", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap genericLittleNewButton
		{
			get
			{
				object obj = ResourceManager.GetObject("genericLittleNewButton", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap NewOptionListItem
		{
			get
			{
				object obj = ResourceManager.GetObject("NewOptionListItem", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap NewOptionsList
		{
			get
			{
				object obj = ResourceManager.GetObject("NewOptionsList", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap NewProject
		{
			get
			{
				object obj = ResourceManager.GetObject("NewProject", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap openOptionsList
		{
			get
			{
				object obj = ResourceManager.GetObject("openOptionsList", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap openProject
		{
			get
			{
				object obj = ResourceManager.GetObject("openProject", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap WelcomeImage
		{
			get
			{
				object obj = ResourceManager.GetObject("WelcomeImage", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Icon WeSayApplicationIcon
		{
			get
			{
				object obj = ResourceManager.GetObject("WeSayApplicationIcon", resourceCulture);
				return ((Icon) (obj));
			}
		}

		internal static Bitmap WeSayConfigMenuSized
		{
			get
			{
				object obj = ResourceManager.GetObject("WeSayConfigMenuSized", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap WeSayImage
		{
			get
			{
				object obj = ResourceManager.GetObject("WeSayImage", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Bitmap WeSayMenuSized
		{
			get
			{
				object obj = ResourceManager.GetObject("WeSayMenuSized", resourceCulture);
				return ((Bitmap) (obj));
			}
		}

		internal static Icon WeSaySetupApplicationIcon
		{
			get
			{
				object obj = ResourceManager.GetObject("WeSaySetupApplicationIcon", resourceCulture);
				return ((Icon) (obj));
			}
		}

		internal static Bitmap WeSaySetupImage
		{
			get
			{
				object obj = ResourceManager.GetObject("WeSaySetupImage", resourceCulture);
				return ((Bitmap) (obj));
			}
		}
	}
}
