#!/bin/sh
HERE=`pwd`
TARGETS='hardy intrepid'
REVISION=`echo $BUILD_NUMBER | sed -e 's/:.*$//'`
export DEBSIGN_KEYID="mono teamcity"
cd ..
VERSION=`dpkg-parsechangelog | grep 'Version:' | sed -e 's/^Version: //'`
dch -v $VERSION.$REVISION "Daily Build"
/home/mono/bin/mpdebuild --vadd .%d --distrib "$TARGETS" --configfile /home/mono/pbuilder/pbuilderrc-%d-new --auto-debsign
#/home/mono/bin/mdput -d ~/pbuilder/results -t PALASO- -f mono_$VERSION.$REVISION\*.changes $TARGETS
cd $HERE
