#!/bin/sh
HERE=`pwd`
#TARGETS='hardy intrepid jaunty'
TARGETS='hardy'
REVISION=`echo $BUILD_NUMBER | sed -e 's/:.*$//'`
MAJOR=`sed -e 's/\.${revision}//' bld/version.txt`
rm -fr build
mkdir -p output/build
cd output/build
cp ../linux/mono/2.0/Debug/wesay-src-$MAJOR.$REVISION.tar.gz wesay-stable-$MAJOR.$REVISION.orig.tar.gz
mkdir wesay-stable-$MAJOR.$REVISION
cd wesay-stable-$MAJOR.$REVISION
tar xzf ../wesay-stable-$MAJOR.$REVISION.orig.tar.gz
cp -r ../../../debian-src-stable debian
export DEBSIGN_KEYID="mono teamcity"
dch -v $MAJOR.$REVISION-1sil1 "Daily Build"
/home/mono/bin/mpdebuild --vadd .%d --distrib "$TARGETS" --configfile /home/mono/pbuilder/pbuilderrc-%d-new --auto-debsign
#/home/mono/bin/mpdebuild --vadd .%d --distrib "$TARGETS" --use-pdebuild-internal --configfile /home/mono/pbuilder/pbuilderrc-%d-new --auto-debsign
#/home/mono/bin/mdput -d ~/pbuilder/results -t LINGNET- -f wesay_$MAJOR.$REVISION\*.changes $TARGETS
#/home/mono/bin/mdput -d ~/pbuilder/results -t PALASO- -f wesay_$MAJOR.$REVISION\*.changes $TARGETS
